In [1]:
##ascesing in the tensords

import torch

In [5]:
tensor = torch.tensor([[10,20,30],[40,50,60],[70,80,90]])

In [6]:
print(tensor.ndim)

2


In [7]:
print(tensor[0,1])

tensor(20)


In [8]:
tensor[0]

tensor([10, 20, 30])

In [9]:
tensor[:,0]

tensor([10, 40, 70])

In [10]:
tensor[:2]

tensor([[10, 20, 30],
        [40, 50, 60]])

In [11]:
print(tensor[1,1:3])

tensor([50, 60])


In [12]:
tensor[[0,2],[1,2]]

tensor([20, 90])

In [13]:
print(tensor >50)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [14]:
print(tensor[tensor >50])

tensor([60, 70, 80, 90])
