In [1]:
import torch


In [5]:
original_tensor = torch.arange(12)

print(original_tensor)
print(original_tensor.nelement())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12


In [6]:
reshaped_tensor = original_tensor.reshape(3, 4)
print(reshaped_tensor)  
print(reshaped_tensor.nelement())
print(reshaped_tensor.ndim)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
12
2


In [7]:
reshaped_tensor = original_tensor.reshape(2,6)
print(reshaped_tensor)  
print(reshaped_tensor.nelement())
print(reshaped_tensor.ndim)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
12
2


In [10]:
##view 
print(original_tensor .is_contiguous())
flattend_tensor = original_tensor .view(-1)
print(flattend_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


SLicing

In [11]:
tensor_a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)  # Accessing element at row 0, column 1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [12]:
print(tensor_a[0])

tensor([1, 2, 3])


In [13]:
tensor_a[:,0]

tensor([1, 4, 7])

In [15]:
tensor_a.shape

torch.Size([3, 3])

Joining

In [17]:
#torch.cat() --> merge tensors along a exsiting dimension

ten_a = torch.tensor([[1,2,3],[4,5,6]])
ten_b = torch.tensor([[7,8,9],[10,11,12]])
joined_tensor = torch.cat((ten_a, ten_b), dim=0)  
joined_tensor_col = torch.cat((ten_a, ten_b), dim=1) # Concatenate along the first dimension
print(joined_tensor)
print(joined_tensor_col)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


In [18]:
orginal_tensor = torch.arange(12)

chunks = torch.chunk(orginal_tensor, 3,dim=0) 

print(chunks)# Split into 3 chunks

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))


In [21]:
orginal_tensor = torch.arange(12)

splits = torch.split(orginal_tensor, 5,dim=0) 

print(splits)# Split into 3 chunks

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11]))


In [ ]:
tensor_orginal = torch.arange(12).reshape(2,3,4)

