In [1]:
import torch

In [2]:
tensor = torch.arange(12)



In [ ]:
reshape_tensor_view = tensor.view(2,6)  
reshape_tensor_reshape = tensor.reshape(2,6)


print(reshape_tensor_view)
print(reshape_tensor_reshape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [5]:
print(reshape_tensor_view.is_contiguous)
reshape_tensor_reshape.is_contiguous

<built-in method is_contiguous of Tensor object at 0x0000021C6A0C47C0>


<function Tensor.is_contiguous>

In [6]:
import torch

In [10]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])


print(tensor_1.ndim)

print(tensor_1.shape)   


dim_0 =torch.stack([tensor_1, tensor_2], dim=0)  # 0: row-wise stacking

dim_1 = torch.stack([tensor_1, tensor_2], dim=1)  # 1: column-wise stacking


print(dim_0)
print(dim_0.ndim)
print(dim_0.shape)

print(dim_1)
print(dim_1.ndim)
print(dim_1.shape)


1
torch.Size([3])
tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
2
torch.Size([3, 2])
